import Link from "next/link";
import { LegalPage } from "@/components/marketing/legal-page";
import { siteConfig } from "@/config/site";
import { buildMetadata } from "@/lib/seo/metadata";

export const metadata = buildMetadata({
  title: "Terms of Service",
  description:
    "The terms that apply to using Oply — accounts, credits, acceptable use, AI output and liability.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="September 2026">
      <p>
        By creating an account or using {siteConfig.name}, you agree to these
        terms.
      </p>

      <h2>1. Your account</h2>
      <p>
        You must provide a valid email address and are responsible for activity
        on your account. Do not share your login. Tell us promptly if you believe
        someone else has access to it.
      </p>

      <h2>2. Credits</h2>
      <p>
        Credits are a prepaid unit of account used to run tools. They are not
        currency, carry no cash value, and are not transferable between accounts.
        Credit costs per tool are published in the product and may be adjusted
        for future generations; credits already in your balance are unaffected.
      </p>
      <p>
        If a generation fails after credits are reserved, those credits are
        returned to your balance automatically.
      </p>

      <h2>3. Payments</h2>
      <p>
        Credit packs are one-time purchases. Prices are shown in USD. Payment is
        processed by a third-party provider — by card through Paddle, which acts
        as Merchant of Record for those transactions, or in crypto through our
        crypto payment provider. Credits are added to your account only after
        that provider confirms the transaction. Blockchain confirmation times
        are outside our control.
      </p>
      <p>
        Credit purchases are final except in the narrow cases set out in the{" "}
        <Link href="/refund-policy">Refund Policy</Link>, which forms part of
        these Terms. Nothing in it limits the consumer rights that apply where
        you live.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You agree not to use {siteConfig.name} to:</p>
      <ul>
        <li>Produce content that is unlawful, defamatory, or infringes rights.</li>
        <li>Impersonate a person or organisation.</li>
        <li>
          Generate spam, malware, deceptive content, or content designed to
          mislead about its origin.
        </li>
        <li>
          Circumvent credit accounting, rate limits, or access another
          user&apos;s data.
        </li>
        <li>Resell access to the service without a written agreement.</li>
      </ul>
      <p>
        We may suspend an account that breaches these terms. Where we do, unused
        credits may be forfeited.
      </p>

      <h2>5. AI output</h2>
      <p>
        Results are generated by an AI model and can be inaccurate, incomplete or
        unsuitable for your purpose. You are responsible for reviewing output
        before you rely on or publish it. {siteConfig.name} makes no
        representation that output is factually correct, original, or fit for any
        particular use, and we do not promise search rankings, sales, or any
        other outcome.
      </p>
      <p>
        Subject to these terms, you own the content you generate and may use it
        commercially.
      </p>

      <h2>6. Availability</h2>
      <p>
        We aim to keep the service available but do not guarantee uninterrupted
        access. Tools depend on third-party AI providers, and we may change,
        suspend or retire individual tools.
      </p>

      <h2>7. Liability</h2>
      <p>
        To the fullest extent permitted by law, {siteConfig.name} is not liable
        for indirect or consequential loss, including lost profits or lost data.
        Our total liability for any claim is limited to the amount you paid us in
        the twelve months before the claim arose.
      </p>

      <h2>8. Termination</h2>
      <p>
        You may stop using the service and request account deletion at any time.
        We may terminate an account for a breach of these terms, or if required
        by law.
      </p>

      <h2>9. Changes</h2>
      <p>
        We may update these terms. Material changes will be reflected in the date
        above, and continuing to use the service after a change means you accept
        it.
      </p>

      <h2>10. Contact</h2>
      <p>
        Questions about these terms:{" "}
        <a href={`mailto:${siteConfig.supportEmail}`}>
          {siteConfig.supportEmail}
        </a>
        .
      </p>
    </LegalPage>
  );
}
